# Algorithms and mathematics of machine learning
## Laboratory 4

To complete the laboratory, use the libraries:
- [numpy](https://numpy.org/)
- [matplotlib](https://matplotlib.org/)

### Task 1

Given the following list of rectangles:
```
rectangles = [("R1", 5, 4.5), ("Wide", 11, 3), ("R2", 4, 6), ("Narrow", 3, 8), ("Square 1", 5, 5), ("Square 2", 4.5, 4.5)]
```
where the subsequent tuple fields are:
- name,
- width,
- height.

#### A)
Based on it, create a structured Numpy array (`np.array(...)`), then sort the rectangles in ascending order by field, and in case of equality, let the name of the rectangle decide (alphabetically).

#### B)
Output the sorted array, in field order:
1. width,
2. height,
3. name.

> NOTE: Where possible, operate on types and functions from the Numpy library.

In [1]:
rectangles = [("R1", 5, 4.5), ("Wide", 11, 3), ("R2", 4, 6), ("Narrow", 3, 8), ("Square 1", 5, 5), ("Square 2", 4.5, 4.5)]

# A
from numpy import array


def sort_func(elements: tuple) -> tuple:
    return elements[1].astype(float) * elements[2].astype(float), elements[0]


np_rectangles = array(rectangles)
np_rectangles = array(sorted(np_rectangles, key=sort_func))
np_rectangles

array([['Square 2', '4.5', '4.5'],
       ['R1', '5', '4.5'],
       ['Narrow', '3', '8'],
       ['R2', '4', '6'],
       ['Square 1', '5', '5'],
       ['Wide', '11', '3']], dtype='<U32')

In [2]:
# B1 - width
np_rectangles = array(rectangles)
np_rectangles[np_rectangles[:, 1].argsort()]

array([['Wide', '11', '3'],
       ['Narrow', '3', '8'],
       ['R2', '4', '6'],
       ['Square 2', '4.5', '4.5'],
       ['R1', '5', '4.5'],
       ['Square 1', '5', '5']], dtype='<U32')

In [3]:
# B2 - height
np_rectangles = array(rectangles)
np_rectangles[np_rectangles[:, 2].argsort()]

array([['Wide', '11', '3'],
       ['R1', '5', '4.5'],
       ['Square 2', '4.5', '4.5'],
       ['Square 1', '5', '5'],
       ['R2', '4', '6'],
       ['Narrow', '3', '8']], dtype='<U32')

In [4]:
# B3 - name
np_rectangles = array(rectangles)
np_rectangles[np_rectangles[:, 0].argsort()]

array([['Narrow', '3', '8'],
       ['R1', '5', '4.5'],
       ['R2', '4', '6'],
       ['Square 1', '5', '5'],
       ['Square 2', '4.5', '4.5'],
       ['Wide', '11', '3']], dtype='<U32')

### Task 2 - 2048 game

There is a square board with side `SIZE' (e.g. 4) for the well-known game 2048 (https://2048game.com/).
Each line contains from 0 to 4 numbers. You need to, using Numpy's construction, simulate movement left, right, up and down the board according to the rules of the game (but **WITHOUT** adding a new tile in a random place). In other words, you need to write four functions:
- `move_left(...)`,
- `move_right(...)`,
- `move_up(...)`,
- `move_down(...)`.

Example of a right move:

The input and output of each of both functions is a 2-dimensional Numpy array.

> NOTE: try to write a function for only one move, and let the other three refer to it in a clever way.

#### Example of a right move:
$\begin{bmatrix}%
2 & 16 & 2 & 2\\
8 & 0 & 0 & 4\\
2 & 0 & 0 & 2\\
4 & 4 & 4 & 4%
\end{bmatrix}$
$move \ right$
$\begin{bmatrix}%
0 & 2 & 16 & 4\\
8 & 0 & 8 & 4\\
0 & 0 & 0 & 4\\
0 & 0 & 8 & 8%
\end{bmatrix}$

In [5]:
board = array([[2, 0, 2, 0], [2, 2, 0, 0], [4, 4, 2, 2], [4, 4, 2, 2]])
board

array([[2, 0, 2, 0],
       [2, 2, 0, 0],
       [4, 4, 2, 2],
       [4, 4, 2, 2]])

In [6]:
from numpy import ndarray, fliplr, flipud, rot90


def move_left(arr: ndarray) -> ndarray:
    for row in range(arr.shape[0]):
        for column in range(arr.shape[1] - 1):
            arr[row] = array(sorted(arr[row], key=lambda x: not x))

            if arr[row][column] == arr[row][column + 1]:
                arr[row][column] *= 2
                arr[row][column + 1] = 0

    return arr


def move_right(arr: ndarray) -> ndarray:
    return fliplr(move_left(fliplr(arr)))


def move_down(arr: ndarray) -> ndarray:
    return rot90(move_left(rot90(arr, 3)))


def move_up(arr: ndarray) -> ndarray:
    return flipud(move_down(flipud(arr)))

In [7]:
# move left
board = array([[2, 0, 2, 0], [2, 2, 0, 0], [4, 4, 2, 2], [4, 4, 2, 2]])
move_left(board)

array([[4, 0, 0, 0],
       [4, 0, 0, 0],
       [8, 4, 0, 0],
       [8, 4, 0, 0]])

In [8]:
# move right
board = array([[2, 0, 2, 0], [2, 2, 0, 0], [4, 4, 2, 2], [4, 4, 2, 2]])
move_right(board)

array([[0, 0, 0, 4],
       [0, 0, 0, 4],
       [0, 0, 8, 4],
       [0, 0, 8, 4]])

In [9]:
# move up
board = array([[2, 0, 2, 0], [2, 2, 0, 0], [4, 4, 2, 2], [4, 4, 2, 2]])
move_up(board)

array([[4, 2, 4, 4],
       [8, 8, 2, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
# move down
board = array([[2, 0, 2, 0], [2, 2, 0, 0], [4, 4, 2, 2], [4, 4, 2, 2]])
move_down(board)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [4, 2, 2, 0],
       [8, 8, 4, 4]])