# Algorytmika i matematyka uczenia maszynowego 
## Laboratorium 10

### Wstęp

Firma produkująca produkty mleczne posiada kilka zamówień do realizacji. Dane są zaprezentowane poniżej.

### Dane

**Ceny składników:**

| Składnik     | Cena (PLN) |
| :---         | ---: |
| Mleko (l)    | 3.5 |
| Cukier (kg)  | 5   |
| Kakao (100g) | 8   |
| Sól (kg)     | 2   |


**Składniki zapisane są w tabeli poniżej:**

| Prod.\Skł.| Mleko (l) | Cukier (kg)  | Kakao (100g) | Sól (kg)    |
| :---      |      ---: |         ---: |         ---: |        ---: |
| Masło     | 5         | 0            | 0            | 0           |
| Czekolada | 1         | 0.1          | 5            | 0.01        |
| Ser żółty | 10        | 0            | 0            | 0.05        |
| Twaróg    | 2         | 0            | 0            | 0.1         |


**Zamówienia klientów:**

| Klient\Prod.| Masło | Czekolada | Ser żółty | Twaróg |
| :---        |  ---: |      ---: |      ---: |   ---: |
| Klient 1    | 10    | 50        | 5         | 5      |
| Klient 2    | 120   | 90        | 15        | 25     |
| Klient 3    | 0     | 10        | 1         | 1      |


> **Uwaga**: Możesz użyć funkcji `plt.table` do wyświetlenia tabeli z wynikami.

> Informacja: Powyższe dane są przykładowe i nie mają przełożenia na faktyczne dane rynkowe.

### Zadanie 1

Korzystając z operacji macierzowych oblicz i odpowiedz na pytania:

#### A) Jaki jest koszt wyprodukowania każdego z produktów?








In [1]:
from numpy import array
from pandas import DataFrame


ingredients = DataFrame(data=array([3.5, 5, 8, 2]), index=['Mleko (l)', 'Cukier (kg)', 'Kakao (100g)', 'Sól (kg)'])
products = DataFrame(
    data=array([[5, 0, 0, 0], [1, 0.1, 5, 0.01], [10, 0, 0, 0.05], [2, 0, 0, 0.1]]),
    index=['Masło', 'Czekolada', 'Ser żółty', 'Twaróg'],
    columns=['Mleko (l)', 'Cukier (kg)', 'Kakao (100g)', 'Sól (kg)']
)
clients = DataFrame(
    data=array([[10, 50, 5, 5], [120, 90, 15, 25], [0, 10, 1, 1]]),
    index=['Klient 1', 'Klient 2', 'Klient 3'],
    columns=['Masło', 'Czekolada', 'Ser żółty', 'Twaróg']
)

In [17]:
cost = products @ ingredients
cost

0
Masło      17.50
Czekolada  44.02
Ser żółty  35.10
Twaróg      7.20

#### B) Ile składników zostanie uzytych na realizację zamówień klientów (każdego osobno i łącznie)?



In [16]:
from pandas import concat


df = clients @ products
df = concat([df, df.sum().to_frame().T], axis=0)
df.index = ['Klient 1', 'Klient 2', 'Klient 3', 'Lącznie']
df

Mleko (l)  Cukier (kg)  Kakao (100g)  Sól (kg)
Klient 1      160.0          5.0         250.0      1.25
Klient 2      890.0          9.0         450.0      4.15
Klient 3       22.0          1.0          50.0      0.25
Lącznie      1072.0         15.0         750.0      5.65

#### C) Zakładając marżę $30\%$ (pomijając wszystkie inne czynniki), ile klienci będą musieli zapłacić za zrealizowanie zamówienia?



In [23]:
price = clients @ cost * 1.3
price.columns = ['Do zapłaty (PLN)']
price

Do zapłaty (PLN)
Klient 1           3363.75
Klient 2           8798.79
Klient 3            627.25

#### D) Jaki jest łączny koszt składników jakie należy zamówić, aby zrealizować wszystkie zamówienia klientów?




In [28]:
whole_cost = (clients @ cost).sum().to_frame()
whole_cost.columns = ['Koszt składników']
whole_cost

Koszt składników
0            9838.3

### Zadanie 2

Napisać skrypt, który przyjmuje dwie macierze $A$ oraz $B$, a następnie wypisuje operacje wykonywane przy mnożeniu obu macierzy.

**Przykład:**

Wejście:

\begin{equation}
A = \begin{pmatrix}
1 & 2 & 1\\
4 & 4 & 5\\
6 & 7 & 7
\end{pmatrix}, 
 B = \begin{pmatrix}
-7 & -7 & 6\\
2 & 1 & -1\\
4 & 5 & -4
\end{pmatrix}
\end{equation}

Wyjście:

```
C[0, 0] = 1 * (-7) + 2 * 2 + 1 * 4 = 1
C[0, 1] = 1 * (-7) + 2 * 1 + 1 * 5 = 0
C[0, 2] = 1 * 6 + 2 * (-1) + 1 * (-4) = 0
C[1, 0] = 4 * (-7) + 4 * 2 + 5 * 4 = 0
C[1, 1] = 4 * (-7) + 4 * 1 + 5 * 5 = 1
C[1, 2] = 4 * 6 + 4 * (-1) + 5 * (-4) = 0
C[2, 0] = 6 * (-7) + 7 * 2 + 7 * 4 = 0
C[2, 1] = 6 * (-7) + 7 * 1 + 7 * 5 = 0
C[2, 2] = 6 * 6 + 7 * (-1) + 7 * (-4) = 1

[[1 0 0]
 [0 1 0]
 [0 0 1]]
```



In [30]:
A = array([[1, 2, 1], [4, 4, 5], [6, 7, 7]])
B = array([[-7, -7, 6], [2, 1, -1], [4, 5, -4]])

In [54]:
from numpy import empty


def get_brackets(a: float) -> str:
    if a < 0:
        return f'({a})'

    return a

result = empty((A.shape[0], B.shape[1])).astype(int)

for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        print(f'C[{i}, {j}] = ', end='')
        for l, k in enumerate(range(A.shape[1])):
            result[i][j] += A[i][k] * B[k][j]
            if l != A.shape[1] - 1:
                print(f' {get_brackets(A[i][k])} * {get_brackets(B[k][j])} ', end='+')
            else:
                print(f' {get_brackets(A[i][k])} * {get_brackets(B[k][j])} ', end='=')

        print(f' {result[i][j]}')

print()
for row in result:
   print(row)

C[0, 0] =  1 * (-7) + 2 * 2 + 1 * 4 = 1
C[0, 1] =  1 * (-7) + 2 * 1 + 1 * 5 = 0
C[0, 2] =  1 * 6 + 2 * (-1) + 1 * (-4) = 0
C[1, 0] =  4 * (-7) + 4 * 2 + 5 * 4 = 0
C[1, 1] =  4 * (-7) + 4 * 1 + 5 * 5 = 1
C[1, 2] =  4 * 6 + 4 * (-1) + 5 * (-4) = 0
C[2, 0] =  6 * (-7) + 7 * 2 + 7 * 4 = 0
C[2, 1] =  6 * (-7) + 7 * 1 + 7 * 5 = 0
C[2, 2] =  6 * 6 + 7 * (-1) + 7 * (-4) = 1

[1 0 0]
[0 1 0]
[0 0 1]
