# Algorithms and mathematics of machine learning
## Laboratory 10

### Entry

A company producing dairy products has several orders to fulfill. The data is presented below.

### Data

**Ingredient prices:**

| Ingredient   | Price (PLN) |
|:-------------|------------:|
| Milk (l)     |         3.5 |
| Sugar (kg)   |           5 |
| Cocoa (100g) |           8 |
| Salt (kg)    |           2 |

**The ingredients are listed in the table below:**

| Product\Ingredient | Milk (l) | Sugar (kg) | Cocoa (100g) | Salt (kg) |
|:-------------------|---------:|-----------:|-------------:|----------:|
| Butter             |        5 |          0 |            0 |         0 |
| Chocolate          |        1 |        0.1 |            5 |      0.01 |
| Yellow cheese      |       10 |          0 |            0 |      0.05 |
| Cottage cheese     |        2 |          0 |            0 |       0.1 |

**Customer orders:**

| Customer\Product | Butter | Chocolate | Yellow cheese | Cottage cheese |
|:-----------------|-------:|----------:|--------------:|---------------:|
| Customer 1       |     10 |        50 |             5 |              5 |
| Customer 2       |    120 |        90 |            15 |             25 |
| Customer 3       |      0 |        10 |             1 |              1 |

> Note: You can use the `plt.table` function to display a table of results.

> Information: The above data are examples and do not reflect actual market data.

### Task 1

Using matrix operations, calculate and answer the questions:

#### A) What is the cost of producing each product?

| Product        | Price (PLN) |
|:---------------|------------:|
| Butter         |        17.5 |
| Chocolate      |       44.02 |
| Yellow cheese  |        35.1 |
| Cottage cheese |         7.2 |

In [1]:
from numpy import array
from pandas import DataFrame


ingredients = DataFrame(
    data=array([3.5, 5, 8, 2]),
    index=['Milk (l)', 'Sugar (kg)', 'Cocoa (100g)', 'Salt (kg)']
)

products = DataFrame(
    data=array([[5, 0, 0, 0], [1, 0.1, 5, 0.01], [10, 0, 0, 0.05], [2, 0, 0, 0.1]]),
    index=['Butter', 'Chocolate', 'Yellow cheese', 'Cottage cheese'],
    columns=['Milk (l)', 'Sugar (kg)', 'Cocoa (100g)', 'Salt (kg)']
)

clients = DataFrame(
    data=array([[10, 50, 5, 5], [120, 90, 15, 25], [0, 10, 1, 1]]),
    index=['Customer 1', 'Customer 2', 'Customer 3'],
    columns=['Butter', 'Chocolate', 'Yellow cheese', 'Cottage cheese']
)

In [2]:
cost = products @ ingredients
cost

0
Butter          17.50
Chocolate       44.02
Yellow cheese   35.10
Cottage cheese   7.20

#### B) How many ingredients will be used to fulfill customer orders (each separately and in total)?

| Customer\Product | Milk (l) | Sugar (kg) | Cocoa (100g) | Salt (kg) |
|:-----------------|---------:|-----------:|-------------:|----------:|
| Customer 1       |      160 |          5 |          250 |      1.25 |
| Customer 2       |      890 |          9 |          450 |      4.15 |
| Customer 3       |       22 |          1 |           50 |      0.25 |
| Total            |     1072 |         15 |          750 |      5.65 |

In [3]:
from pandas import concat


df = clients @ products
df = concat([df, df.sum().to_frame().T], axis=0)
df.index = ['Customer 1', 'Customer 2', 'Customer 3', 'Total']
df

Milk (l)  Sugar (kg)  Cocoa (100g)  Salt (kg)
Customer 1     160.0         5.0         250.0       1.25
Customer 2     890.0         9.0         450.0       4.15
Customer 3      22.0         1.0          50.0       0.25
Total         1072.0        15.0         750.0       5.65

#### C) Assuming a margin of $30\%$ (ignoring all other factors), how much will customers have to pay to fulfill their order?

| Customer   | To pay (PLN) |
|:-----------|-------------:|
| Customer 1 |      3363.75 |
| Customer 2 |      8798.79 |
| Customer 3 |       627.25 |

In [4]:
price = clients @ cost * 1.3
price.columns = ['To pay (PLN)']
price

To pay (PLN)
Customer 1       3363.75
Customer 2       8798.79
Customer 3        627.25

#### D) What is the total cost of ingredients that must be ordered to fulfill all customer orders?

| Cost of ingredients |
|:--------------------|
| 9839.3              |

In [5]:
whole_cost = (clients @ cost).sum().to_frame()
whole_cost.columns = ['Cost of ingredients']
whole_cost

Cost of ingredients
0               9838.3

### Task 2

Write a script that takes two matrices $A$ and $B$ and then prints the operations performed when multiplying both matrices.

**Example:**

Input:
\begin{equation}
A = \begin{pmatrix}
1 & 2 & 1\\
4 & 4 & 5\\
6 & 7 & 7
\end{pmatrix}, 
 B = \begin{pmatrix}
-7 & -7 & 6\\
2 & 1 & -1\\
4 & 5 & -4
\end{pmatrix}
\end{equation}

Output:
```
C[0, 0] = 1 * (-7) + 2 * 2 + 1 * 4 = 1
C[0, 1] = 1 * (-7) + 2 * 1 + 1 * 5 = 0
C[0, 2] = 1 * 6 + 2 * (-1) + 1 * (-4) = 0
C[1, 0] = 4 * (-7) + 4 * 2 + 5 * 4 = 0
C[1, 1] = 4 * (-7) + 4 * 1 + 5 * 5 = 1
C[1, 2] = 4 * 6 + 4 * (-1) + 5 * (-4) = 0
C[2, 0] = 6 * (-7) + 7 * 2 + 7 * 4 = 0
C[2, 1] = 6 * (-7) + 7 * 1 + 7 * 5 = 0
C[2, 2] = 6 * 6 + 7 * (-1) + 7 * (-4) = 1

[[1 0 0]
 [0 1 0]
 [0 0 1]]
```

In [6]:
A = array([[1, 2, 1], [4, 4, 5], [6, 7, 7]])
B = array([[-7, -7, 6], [2, 1, -1], [4, 5, -4]])

In [7]:
from numpy import empty


def get_brackets(a: float) -> str:
    return f'({a})' if a < 0 else a


result = empty((A.shape[0], B.shape[1])).astype(int)

for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        print(f'C[{i}, {j}] = ', end='')
        for l, k in enumerate(range(A.shape[1])):
            result[i][j] += A[i][k] * B[k][j]
            if l != A.shape[1] - 1:
                print(f' {get_brackets(A[i][k])} * {get_brackets(B[k][j])} ', end='+')
            else:
                print(f' {get_brackets(A[i][k])} * {get_brackets(B[k][j])} ', end='=')

        print(f' {result[i][j]}')

print()
for row in result:
   print(row)

C[0, 0] =  1 * (-7) + 2 * 2 + 1 * 4 = 1
C[0, 1] =  1 * (-7) + 2 * 1 + 1 * 5 = 0
C[0, 2] =  1 * 6 + 2 * (-1) + 1 * (-4) = 0
C[1, 0] =  4 * (-7) + 4 * 2 + 5 * 4 = 0
C[1, 1] =  4 * (-7) + 4 * 1 + 5 * 5 = 1
C[1, 2] =  4 * 6 + 4 * (-1) + 5 * (-4) = 0
C[2, 0] =  6 * (-7) + 7 * 2 + 7 * 4 = 0
C[2, 1] =  6 * (-7) + 7 * 1 + 7 * 5 = 0
C[2, 2] =  6 * 6 + 7 * (-1) + 7 * (-4) = 1

[1 0 0]
[0 1 0]
[0 0 1]
